FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y systemd systemd-sysv openssh-server sudo curl wget lsb-release pacemaker corosync apache2 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash devops && echo "devops:devops" | chpasswd && adduser devops sudo

RUN mkdir /var/run/sshd
EXPOSE 22

CMD ["/sbin/init"] 