FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y openssh-server sudo curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash devops && echo "devops:devops" | chpasswd && adduser devops sudo

RUN mkdir /var/run/sshd

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 22 8080

ENTRYPOINT ["/entrypoint.sh"] 